default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:  <%= ENV['BUDGET_APP_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: budget_app
  username: postgres
  password:  <%= ENV['BUDGET_APP_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: budget_app_test
  username: postgres
  password:  <%= ENV['BUDGET_APP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: budget_app_production
  username: budget_app_user
  password: <%= ENV['BUDGET_APP_DATABASE_PASSWORD'] %>
  host: <%= ENV['BUDGET_APP_DATABASE_HOST'] %>
